### ISSUE TITLE
Implicit pybind11 dependency 

### ISSUE THREAD

**Issue by bdanielby** [blue-yonder/turbodbc#113] opened 2017-07-14 09:21 UTC
When you try the compilation from source and you haven't installed `pybind11` then `setup.py` raises the error message `ImportError: No module named pybind11`, so the `pybind11` dependency seems to be missing in the explicit setup dependencies.

**Comment by MathMagique** [comment] 2017-07-14 13:23
Hi! Unfortunately, this is true. I have tried adding pybind11 to the setup dependencies, but then the error message just changes. I am closing this as a duplicate of #59, where you can also find links to a similar issue in pybind11's very own example project.

**Closed by MathMagique** 2017-07-14 13:23 UTC
